
#sudo: required
# Build all branches, *including* gh-pages:
branches:
  only:
  - gh-pages
  - /.*/
   
services:
  - docker
  
script:
  - docker-compose -f ./pingdirectory/build.test.yml up

notifications:
  slack: pingidentity:FECD6DfLcWlWRsUR9xqeg1Yb