sudo: required
# Build all branches, *including* gh-pages:
branches:
  only:
  - gh-pages
  - /.*/
   
services:
  - docker

script:
  #- docker-compose -f ./pingdirectory/build.test.yml up
  - docker image build -t samirgandhi/pingfederate ./pingfederate
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push samirgandhi/pingfederate

notifications:
  slack: pingidentity:FECD6DfLcWlWRsUR9xqeg1Yb